sys_shd (context & workflow)
WattRex/System-Tools pull request #30
Opened 2023-11-16 11:32 UTC by javibu13

2023-11-16 14:08 UTC, mariuscrsn requested changes

2023-11-16 14:08 UTC, mariuscrsn commented on code/sys_shd/src/system_shared_tool/sys_shd_channels.py
> +    def delete_until_last(self, timeout: int = DEFAULT_CHAN_TIMEOUT) -> None:
Remove timeout from here, it must use unblocking

2023-11-16 14:08 UTC, mariuscrsn commented on code/sys_shd/src/system_shared_tool/sys_shd_channels.py
> +    def delete_until_last(self, timeout: int = DEFAULT_CHAN_TIMEOUT) -> None:
Use default timeout on receive_data

2023-11-16 14:49 UTC, javibu13 commented on code/sys_shd/src/system_shared_tool/sys_shd_channels.py
> +    def delete_until_last(self, timeout: int = DEFAULT_CHAN_TIMEOUT) -> None:
Done.

2023-11-17 07:43 UTC, mariuscrsn approved these changes

2023-11-17 07:45 UTC, merged