Add try|except to update_config_params function
WattRex/System-Tools pull request #32
Opened 2023-11-22 11:56 UTC by javibu13

Done #31

2023-11-22 22:54 UTC, mariuscrsn requested changes

2023-11-22 22:54 UTC, mariuscrsn commented on code/sys_conf/src/system_config_tool/sys_conf.py
> +        log.info(error)
Add an error message

2023-11-22 22:54 UTC, mariuscrsn commented on code/sys_conf/src/system_config_tool/sys_conf.py
> +        log.info(error)
Use error level not info, or warning at least

2023-11-22 22:54 UTC, mariuscrsn commented on code/sys_conf/src/system_config_tool/sys_conf.py
> +        if custom_params is not None and len(custom_params) > 0:
Second condition is not necessary

2023-11-23 11:58 UTC, javibu13 commented on code/sys_conf/src/system_config_tool/sys_conf.py
> +        if custom_params is not None and len(custom_params) > 0:
Removed.

2023-11-23 11:59 UTC, javibu13 commented on code/sys_conf/src/system_config_tool/sys_conf.py
> +        log.info(error)
Changed to warning because may be one section is not desired to be changed in config_params file and this situation is not an error.

2023-11-23 12:44 UTC, mariuscrsn approved these changes

2023-11-23 12:45 UTC, merged